name: yourevent
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"



dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.15
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  bloc: ^8.1.4
  google_sign_in: ^6.2.2
  auto_route: ^9.2.2
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.3
  flutter_localizations:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  retrofit_generator: ^9.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  auto_route_generator: 9.0.0
  json_serializable: ^6.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
