name: yourevent
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_svg: ^2.0.10
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  bloc: ^8.1.4
  google_sign_in: ^6.2.1
  auto_route: ^9.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  auto_route_generator: 9.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
